CREATE TABLE saved_traveler_results (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    placeName TEXT NOT NULL,
    countryName TEXT NOT NULL,
    price TEXT NOT NULL,
    carrier TEXT NOT NULL,
    departure TEXT NOT NULL,
);