CREATE TABLE IF NOT EXISTS saved_flights (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    place_name TEXT NOT NULL,
    country_name TEXT NOT NULL,
    price TEXT NOT NULL,
    carrier TEXT NOT NULL,
    departure TEXT NOT NULL
);
